### PR TITLE
Add stroke_color option to generate legend tool

### PR DESCRIPTION
**Pull request by edplato**
This feature adds the  `--stroke_color` option to the `oe_generate_legend.py` tool. The option adds an input stroke color around the label text and ticks in order to provide greater visibility when viewed over light and dark backgrounds.

If no `--stroke_color` is provided, then it will default to `False` and the option will not be used unlike the default `--label_color` which defaults to black.

**Examples:**
- **Existing default black label:**
sample_discretew

- **Changes with white label color and black stroke color:**
sample_discrete

**Additional considerations:**

- There may be room for improvement on the best stroke `linewidth` to use.
Example with stroke `linewidth` of `1`:
sample_continuousclass100
Example with stroke `linewidth` of `0.75`:
sample_continuousclass075
- Example with white label color and white stroke color. Using the same color for both stroke and label results in a quasi bold text:
sample_discreted

### CODE REVIEW

**Comment by jtroberts** [comment]
Looks great to me! Thanks for including the examples.

**Comment by mcechini** [comment]
Ditto, looks really good to me too!

**Comment by jtroberts** [comment]
@mcechini thoughts on whether to merge this in 1.4.0 or 1.3.8?

**Comment by mcechini** [comment]
Sounds like Ed would like it sooner than later in GIBS, which means we'll want it in 1.3.8 and 1.4.0.  And as long as the default behavior is the same before and after merge, then I'm ok with that.  Slightly more work to merge I suppose.

**Pull request merged**
