### PR TITLE
ONEARTH-670 Support for CentOS 8

### PR DESCRIPTION
**Pull request by jtroberts**

### CODE REVIEW

**Review by dtchou802 — APPROVED** [review]

**Comment by mcechini** [comment]
When I install the RPM, I'm seeing `/usr/libexec/platform-python` at the top of mrfgen and oe_vectorgen, which is causing some issues for me.  The code seems to still have the `/usr/bin/env python3`.  I'm not sure where that is getting changed.

**Comment by jtroberts** [comment]
That's being added by the pathfix.py script in the gibs-gdal RPMs that is supposed to correct the python shebangs. I'll take a look to see if there is a better approach.

**Comment by jtroberts** [comment]
@mcechini please check out the new build: https://github.com/nasa-gibs/onearth/releases/download/v1.4.0/onearth-1.4.0-5.el8.tar.gz

**Comment by mcechini** [comment]
Updated RPMs are installing fine.  The only issue I'm having is that when I try to run oe_vectorgen, it's not able to import `oe_create_mvt_mrf.py`, which is in /usr/share/onearth/vectorgen/.  

I notice that when I install the CentOS 7 RPMs, I'm seeing oe_vectorgen symlinked: `/usr/bin/oe_vectorgen -> ../share/onearth/vectorgen/oe_vectorgen.py`. In CentOS 8, we're installing directly to /usr/bin/oe_vectorgen.

I haven't tested oe_configure_layer yet, but I suspect it may have a similar issue where it may not be able to reach the `oe_configure_remote_layers.py` and `oe_configure_remote_layers.py` files.

**Comment by jtroberts** [comment]
@mcechini this build should hopefully fix those issues: https://github.com/nasa-gibs/onearth/releases/download/v1.4.0/onearth-1.4.0-6.el8.tar.gz

**Review by mcechini — APPROVED** [review]
Looks like it's working!

**Pull request merged**
